# Generated by Django 4.2.3 on 2023-07-18 06:39

import computer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='', validators=[computer.models.validate_file_size, computer.models.validate_file_type])),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=20)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ram', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_code', models.IntegerField(unique=True)),
                ('quantity', models.IntegerField()),
                ('unit_rate', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.computerspecification')),
            ],
        ),
    ]
