# Generated by Django 4.2.3 on 2023-07-19 11:21

import computer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_rename_computer_computer_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.FileField(default='', upload_to='', validators=[computer.models.validate_file_size, computer.models.validate_file_type]),
            preserve_default=False,
        ),
    ]
